echo -e '\e[40m\e[97m'
echo -e '                                                            '
echo -e '                                           /ψψ              '
echo -e '                                          | ψψ              '
echo -e '            /ψψψψψψψ /ψ/ψψψψψψ  /ψψψψψψ   | ψψ              '
echo -e '           /ψψ_____/| ψψ___ ψψ /ψψ__  ψψ  | ψψ              '
echo -e '          | ψψ      | ψψ   |_/| ψψ  \ ψψ|ψψψψψψψψ           '
echo -e '          | ψψ      | ψψ      | ψψ  | ψψ  | ψψ_/            '
echo -e '          | ψψψψψψψψ| ψψ      |  ψψψψψ /  | ψψψψψψ          '
echo -e '           \_______/|__/      | ψψ____/   |______/          '
echo -e '                              | ψψ  /ψψ       /ψψ           '
echo -e '                              |__/ | ψψ      | ψψ           '
echo -e '       /ψψψψψψψ  /ψψψψψψ   /ψψψψψψψ| ψψ      | ψψ   /ψψ     '
echo -e '      /ψψ_____/ /ψψ__  ψψ /ψψ_____/| ψψψψψψψ | ψψ /ψψ       '
echo -e '     | ψψ      | ψψ  \ ψψ| ψψ      | ψψ__  ψψ| ψψψψ         '
echo -e '     | ψψ      | ψψ  | ψψ| ψψ      | ψψ  \ ψψ| ψψ\ ψψ       '
echo -e '     | ψψψψψψψψ|  ψψψψψ /| ψψψψψψψψ| ψψ  | ψψ| ψψ \  ψψ     '
echo -e '      \_______/| ψψ____/  \_______/|__/  |__/|__/  \__/     '
echo -e '               | ψψ                                         '
echo -e '               |__/                                         '
echo -e '\e[0m'
echo -e '\e[40m\e[93m         psi.crypto: https://discord.gg/Et92Ncafsk          \e[0m'
echo -e '\e[40m\e[92m          HackenDAO: https://x.com/HackenDAO                \e[0m'
echo -e '\e[40m\e[97m             RawBox: https://x.com/rawbox_tech              \e[0m'
echo -e '\e[40m\e[96m             zkSync: https://t.co/thgiIXqtlA                \e[0m'
echo -e '                                                            '
